Side w1
luciano-ilha/Using-Bootstrap pull request #1
Opened 2020-06-05 13:00 UTC by luciano-ilha

This project contains a clone of the Newsweek website, was done with HTML, CSS Positioning and Layout (Including Grid and Flexbox), Media Query, and Bootstrap, using mobile-first approach. After finish mobile-first, done 768px view and 992px for better responsiveness.

These are the main concepts applied in this project:

CSS Positioning and Layout (Including Grid and Flexbox)
Media Query and Overall Responsiveness
Image embedding
Hover effects and other dynamic responses

2020-06-05 20:14 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-05 20:15 UTC, addod19 requested changes
## Status: Require changes:recycle: :traffic_light: 

Hi @luciano-ilha, great job with this project :+1: Professional commit messages :100: Very descriptive PR :slightly_smiling_face: README professional :100: 
Let us improve our code and make it better by addressing the comment below:
- Files not related to the project must not be committed, let add it to a gitignore file
![gih](https://user-images.githubusercontent.com/46388113/83918307-fc06de00-a767-11ea-81f6-b56efc3f15fd.png)
- The Newsletter and the Subscribe must have the same height. Currently
![ffr](https://user-images.githubusercontent.com/46388113/83918577-936c3100-a768-11ea-968d-18f678538770.png)

Kindly make these changes and submit another code review :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-08 10:04 UTC, peterrobert commented
### PULL REQUEST UNDER REVIEW BY PETER ROBERT (TSE)

2020-06-08 11:09 UTC, peterrobert reviewed
### CHANGES REQUIRED :recycle: 
A great project so far :+1: Everything is working perfectly. Great commit messages :+1:  However there is a few things that require to be changed before i can approve this project. 

- [x] Kindly check the links to some of your images. They appear broken.

![broken_link_ing](https://user-images.githubusercontent.com/32361963/84023732-4d45e600-a991-11ea-80bd-c458674a68db.jpg)

- [x] I have added other changes below :arrow_down: 

**When you through kindly submit the project for another review**

**If you have any questions kindly reach out to me via slack** @peterrobert 

### HAPPY CODING

2020-06-08 11:09 UTC, peterrobert commented on styles/style.css
> +}
Try using bootstrap display block class [here](https://getbootstrap.com/docs/4.0/utilities/display/) is a link to bootstrap display property

2020-06-08 11:09 UTC, peterrobert commented on styles/style.css
> +}
Try using bootstrap display block class [here](https://getbootstrap.com/docs/4.0/utilities/display/) is a link to bootstrap display property

2020-06-08 12:37 UTC, luciano-ilha commented on styles/style.css
> +}
Done! Thanks for the help

2020-06-08 12:38 UTC, luciano-ilha commented on styles/style.css
> +}
d-flex you mean?! Done! Tks for the help

2020-06-08 13:06 UTC, HADDADSOHAIB requested changes
> ### Pull Request under the review by Sohaib Haddad. (TSE)
### Change Required :recycle: 

### Hello @luciano-ilha     :handshake: 

### Good job so far :clap:  your project looks like the original :medal_sports: 

### there are some changes to get the project approved :point_down:
- You should always check your project using the validators before asking for a review, please fix all the errors:
![Screenshot from 2020-06-08 13-59-05](https://user-images.githubusercontent.com/26064042/84033260-7d40b980-a990-11ea-94cb-a8b4fc147d51.png)
- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. (Students were asked to use this one, so in most cases their code should be already validated) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
- Please do as the previous TSE asks and remove files not related to the project, (I am talking about .DS_store):
- [x] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- Please remove the comment from you code:
- [x] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png)

### Once your done with the changes, ask for another code review.

2020-06-08 23:34 UTC, voscarmv commented
# Pull Request Under Review by Oscar Mier (TSE) 👨‍💻 🐦

2020-06-08 23:41 UTC, voscarmv requested changes
# Impressive work so far @luciano-ilha 👀 👏 👏 👏 
## However, a few changes are still required 🧰 🔨 🔧 
- Your use of the semantic `<nav>` and `<footer>` tags is good, but I don't see any `<main>` tag indicating the central content of your page. I also don't see any `<section>` tags being used to indicate the different sections in your page. Please improve your use of Semantic HTML and re-submit for review! Screenshot:
![image](https://user-images.githubusercontent.com/2739245/84090371-34502b80-a9b7-11ea-92db-acffa6abd82a.png)

### Once you implement these changes re-submit for review 😄 👍 
## Questions? Comments? Contact me on [Twitter](http://www.twitter.com/voscarm) or [Linkedin](http://www.linkedin/in/oscar-mier) 🧑‍💻 💬 🧑‍💻 
## Happy hacking! 🧠 ⌨️ 🖥️

2020-06-09 10:37 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-09 10:38 UTC, andresporras3423 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello @luciano-ilha** 
Amazing job :clap: :clap: you have passed all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the master branch

Keep going like this,

Oscar Andrés Russi Porras

2020-06-09 10:47 UTC, merged